#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo systemctl start nginx

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restarting nginx
sudo systemctl restart nginx

echo -e "\nCompleted. ✅\n"
